stolostron/cm-cli

- README.md
> Change install method

- README.md
- docs/applier.md
- docs/cluster.md
- pkg/cmd/applierscenarios/applierscenarios.go
- pkg/cmd/attach/cluster/exec.go
- pkg/cmd/create/cluster/exec.go
- pkg/cmd/delete/cluster/cmd.go
- pkg/cmd/delete/cluster/exec.go
- pkg/cmd/detach/cluster/exec.go
- pkg/resources/resources.go
- pkg/resources/resources_test.go
- sonar-project.properties
> Add capability to download scenario templates

- pkg/cmd/delete/cluster/exec.go
- pkg/cmd/delete/cluster/exec_test.go
- pkg/cmd/detach/cluster/exec.go
- pkg/cmd/detach/cluster/exec_test.go
cm cluster delete has the wrong scenario
> Fix few bugs

- Makefile
- README.md
> Fix plugin creation

- .github/workflows/release.yaml
- CHANGELOG.md
> Add release workflow

- docs/cluster.md
- pkg/cmd/attach/cluster/cmd.go
- pkg/cmd/attach/cluster/scenario/attach/values-template.yaml
- pkg/cmd/attach/cluster/test/unit/values-with-data.yaml
- pkg/cmd/create/cluster/scenario/create/values-template.yaml
- pkg/cmd/create/cluster/test/unit/values-fake-aws.yaml
- pkg/cmd/create/cluster/test/unit/values-fake-azure.yaml
- pkg/cmd/create/cluster/test/unit/values-fake-gcp.yaml
- pkg/cmd/create/cluster/test/unit/values-fake-openstack.yaml
- pkg/cmd/create/cluster/test/unit/values-fake-vsphere.yaml
- pkg/cmd/delete/cluster/cmd.go
- pkg/cmd/delete/cluster/scenario/delete/values-template.yaml
- pkg/cmd/delete/cluster/test/unit/values-fake.yaml
- pkg/cmd/delete/cluster/test/unit/values-with-data.yaml
- pkg/cmd/detach/cluster/cmd.go
- pkg/cmd/detach/cluster/scenario/detach/values-template.yaml
- pkg/cmd/detach/cluster/test/unit/values-fake.yaml
- pkg/cmd/detach/cluster/test/unit/values-with-data.yaml
- pkg/cmd/scale/cluster/cmd.go
- pkg/cmd/scale/cluster/scenario/scale/values-default.yaml
- pkg/cmd/scale/cluster/scenario/scale/values-template.yaml
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
> Complete rename of --name to --cluster

- .github/workflows/release.yaml
> Use go 1.16 in workflow

- CHANGELOG.md
- pkg/cmd/attach/cluster/cmd.go
- pkg/cmd/attach/cluster/exec.go
- pkg/cmd/attach/cluster/exec_test.go
- pkg/cmd/attach/cluster/scenario/attach/managedcluster/import_crd.yaml
- pkg/cmd/attach/cluster/scenario/attach/managedcluster/import_yaml.yaml
- pkg/cmd/attach/cluster/test/unit/import_result.yaml_crd.yaml
- pkg/cmd/attach/cluster/test/unit/import_result.yaml_yaml.yaml
https://github.com/open-cluster-management/cm-cli/issues/30
> split manual import cmd

- pkg/clusterpoolhost/clusterpool.go
- pkg/clusterpoolhost/scenario/create/clusterpool/common/clusterpool_cr.yaml
- pkg/clusterpoolhost/scenario/create/clusterpool/common/creds_secret_cr.yaml
- pkg/clusterpoolhost/scenario/create/clusterpool/common/install_config_secret_cr.yaml
- pkg/clusterpoolhost/scenario/create/clusterpool/common/namespace.yaml
- pkg/clusterpoolhost/scenario/create/clusterpool/common/pull_secret_cr.yaml
- pkg/clusterpoolhost/scenario/create/clusterpool/common/values-template.yaml
- pkg/cmd/create/clusterpool/exec.go
- pkg/cmd/get/clusterpools/cmd.go
- pkg/cmd/get/clusterpools/exec.go
> fix cp creation

- pkg/clusterpoolhost/clusterclaim.go
This PR resolves #72 by notifying the user of `StatusReasonForbidden` -type errors but ignoring the error and continuing to poll, skipping claim status checks.
> Ignore StatusReasonForbidden-type errors when polling a ClusterClaim

- pkg/cmd/attach/cluster/cmd.go
- pkg/cmd/attach/clusterclaim/cmd.go
- pkg/cmd/create/cluster/cmd.go
- pkg/cmd/delete/cluster/cmd.go
- pkg/cmd/detach/cluster/cmd.go
- pkg/cmd/enable/addons/cmd.go
- pkg/cmd/get/credentials/cmd.go
- pkg/cmd/scale/cluster/cmd.go
- pkg/cmd/version/cmd.go
https://github.com/open-cluster-management/cm-cli/issues/69 (only available on RHACM)
> change message only available on RHACM

- pkg/clusterpoolhost/clusterclaim.go
https://github.com/open-cluster-management/cm-cli/issues/74 `cm get cc` crash
> fix issue_74 too many separator when err

- pkg/clusterpoolhost/clusterclaimcontext.go
https://github.com/open-cluster-management/cm-cli/issues/70 remove switch context
> Remove switch to cph

- pkg/clusterpoolhost/clusterclaim.go
- pkg/clusterpoolhost/clusterclaimcontext.go
- pkg/cmd/get/clusterclaim/exec.go
> Fix No message in std when cm get cc <cluster

- pkg/cmd/with/cmd.go
> Disable cm with cph

- .gitignore
- .krew.yaml
- CHANGELOG.md
- Makefile
- build/check-copyright.sh
- build/run-functional-tests-clean.sh
- build/run-functional-tests.sh
- pkg/cmd/attach/cluster/exec.go
- pkg/cmd/attach/clusterclaim/exec.go
- pkg/cmd/version/cmd.go
- pkg/cmd/version/exec.go
- pkg/cmd/version/exec_test.go
- pkg/helpers/client.go
- pkg/helpers/version.go
- test/functional/kubestatus.go
- test/functional/resources/multiclusterhubs_cr.yaml
https://github.com/open-cluster-management/cm-cli/issues/119
> Add generate krew.yaml and cm version

- CHANGELOG.md
- docs/help/cm_attach_cluster.md
- docs/help/cm_attach_clusterclaim.md
- docs/help/cm_create_cluster.md
- docs/help/cm_create_clusterclaim.md
- pkg/cmd/attach/cluster/cmd.go
- pkg/cmd/attach/cluster/exec.go
- pkg/cmd/attach/cluster/exec_test.go
- pkg/cmd/attach/cluster/options.go
- pkg/cmd/attach/clusterclaim/cmd.go
- pkg/cmd/attach/clusterclaim/exec.go
- pkg/cmd/attach/clusterclaim/options.go
- pkg/cmd/create/cluster/cmd.go
- pkg/cmd/create/cluster/exec.go
- pkg/cmd/create/cluster/exec_test.go
- pkg/cmd/create/cluster/options.go
- pkg/cmd/create/clusterclaim/cmd.go
- pkg/helpers/client.go
- pkg/helpers/klusterletaddons.go
https://github.com/open-cluster-management/cm-cli/issues/120
> Wait attach cluster/attach clusterclaim and create cluster

- CHANGELOG.md
- pkg/clusterpoolhost/clusterclaim.go
https://github.com/open-cluster-management/cm-cli/issues/124
> Error when creating a cc from a pool

- CHANGELOG.md
- docs/help/cm_console_clusterclaims.md
- docs/help/cm_create_clusterclaim.md
- docs/help/cm_run_clusterclaim.md
- pkg/clusterpoolhost/clusterclaim.go
- pkg/cmd/console/clusterclaim/cmd.go
- pkg/cmd/console/clusterclaim/exec.go
- pkg/cmd/console/clusterclaim/options.go
- pkg/cmd/create/clusterclaim/cmd.go
- pkg/cmd/create/clusterclaim/exec.go
- pkg/cmd/create/clusterclaim/options.go
- pkg/cmd/get/clusterclaim/exec.go
- pkg/cmd/run/clusterclaim/cmd.go
- pkg/cmd/run/clusterclaim/exec.go
- pkg/cmd/run/clusterclaim/options.go
https://github.com/open-cluster-management/cm-cli/issues/129
> Add create creds

- .github/workflows/krew.yaml
> add checkout

- docs/cluster.md
- docs/clusterpool.md
- pkg/clusterpoolhost/clusterpool.go
- pkg/cmd/get/clusterpools/cmd.go
- pkg/cmd/get/clusterpools/exec.go
- pkg/cmd/get/clusterpools/options.go
- Add support for listing a single clusterpool by specifying it's name
- Add support for throwing an error and non-zero return code if the specified name does not exist
> Single clusterpool

- pkg/clusterpoolhost/clusterclaim.go
This fixes two issues with `--timeout` when using `cm get clusterclaim`.
1) Setting `--timeout 0` will now return immediately instead of continuing to run indefinitely.
```
$ cm get cc ray-idp-hub-1 --timeout 0
clusterclaim ray-idp-hub-1 is not running (0)
error: one or more clusterclaims are not running: ray-idp-hub-1
```
2) Setting `--timeout n` with n > 0 will now return in n minutes rather than n+2 minutes.
> get clusterclaim: fix timeout wait

- .copyrightignore
- go.mod
- go.sum
- pkg/clusterpoolhost/clusterclaim.go
- pkg/cmd/attach/cluster/exec_test.go
- test/unit/crd/external/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
- test/unit/crd/external/0000_00_work.open-cluster-management.io_manifestworks.crd.yaml
https://github.com/stolostron/cm-cli/issues/148
> Fix error message when create cc

- CHANGELOG.md
- pkg/clusterpoolhost/clusterpoolhostcontext.go
https://github.com/stolostron/cm-cli/issues/162
> update login prompt

- CHANGELOG.md
- pkg/clusterpoolhost/clusterclaim.go
https://github.com/stolostron/cm-cli/issues/167
> Add error message is cc has no ns

- pkg/clusterpoolhost/clusterclaim.go
> Fix running message

- api/cm-cli/v1alpha1/crd/cm-cli.open-cluster-management.io_printclusterpools.yaml
- api/cm-cli/v1alpha1/printclusterpool.go
> Add cp standby

- pkg/cmd/attach/hostedcluster/cmd.go
- pkg/cmd/attach/hostedcluster/exec.go
- pkg/helpers/server.go
- pkg/helpers/version.go
> better detect when Hypershift install

- pkg/cmd/detach/cluster/cmd.go
- pkg/cmd/scale/clusterpool/exec.go
> Alias detach clusterclaim with cluster

- go.mod
- go.sum
- pkg/clusterpoolhost/clusterclaim.go
> Upgrade to latest hive

- docs/help/cm_create.md
- docs/help/cm_create_work.md
- docs/help/cm_delete_work.md
- pkg/clusterpoolhost/clusterpool.go
- pkg/cmd/create/cluster/exec.go
> update doc and code smells

- CHANGELOG.md
- pkg/cmd/attach/cluster/cmd.go
- pkg/cmd/attach/cluster/exec.go
- pkg/cmd/attach/cluster/options.go
https://github.com/stolostron/cm-cli/issues/197
> Add in cm attach cluster the --cluster-kubecontext

- CHANGELOG.md
- pkg/clusterpoolhost/clusterclaim.go
- pkg/clusterpoolhost/clusterdeployment.go
- pkg/clusterpoolhost/clusterpoolhostcontext.go
- pkg/cmd/console/cmd.go
- pkg/cmd/console/hosted/cmd.go
- pkg/cmd/console/hosted/exec.go
- pkg/cmd/console/hosted/options.go
- pkg/cmd/get/clusterclaim/cmd.go
- pkg/cmd/get/clusterclaim/exec.go
- pkg/helpers/client.go
- pkg/hypershift/hypershift.go
https://github.com/stolostron/cm-cli/issues/201
> Add console for hosted and get kubeconfig for cc

- CHANGELOG.md
- docs/help/cm_console_cluster.md
- docs/help/cm_create_clusterclaim.md
- docs/help/cm_set_cluster.md
- pkg/cmd/set/cluster/cmd.go
- pkg/cmd/set/cluster/exec.go
- pkg/cmd/set/cluster/options.go
https://github.com/stolostron/cm-cli/issues/210
> Hibernate cronjob test

- CHANGELOG.md
- pkg/clusterpoolhost/clusterclaim.go
- pkg/clusterpoolhost/clusterclaimcontext.go
- pkg/cmd/create/clusterclaim/cmd.go
- pkg/cmd/create/clusterclaim/exec.go
- pkg/cmd/create/clusterclaim/options.go
- pkg/cmd/hibernate/clusterclaim/cmd.go
- pkg/cmd/run/clusterclaim/exec.go
- pkg/cmd/run/clusterclaim/options.go
- pkg/cmd/set/cluster/cmd.go
- pkg/cmd/set/clusterclaim/cmd.go
- pkg/cmd/set/clusterclaim/exec.go
- pkg/cmd/set/clusterclaim/options.go
- pkg/cmd/set/cmd.go
https://github.com/stolostron/cm-cli/issues/212
https://github.com/stolostron/cm-cli/issues/209
> work on skipschule

- CHANGELOG.md
- pkg/clusterpoolhost/clusterclaim.go
- pkg/cmd/create/cmd.go
- pkg/cmd/create/hypershiftdeployment/cmd.go
- pkg/cmd/create/hypershiftdeployment/exec.go
- pkg/cmd/create/hypershiftdeployment/options.go
- pkg/cmd/create/hypershiftdeployment/scenario/create/hd.yaml
- pkg/cmd/create/hypershiftdeployment/scenario/create/values-template.yaml
- pkg/cmd/create/hypershiftdeployment/scenario/resources.go
- pkg/cmd/delete/clusterclaim/exec.go
- pkg/cmd/delete/cmd.go
- pkg/cmd/delete/hypershiftdeployment/cmd.go
- pkg/cmd/delete/hypershiftdeployment/exec.go
- pkg/cmd/delete/hypershiftdeployment/options.go
- pkg/hypershift/hypershift.go
https://github.com/stolostron/cm-cli/issues/214
https://github.com/stolostron/cm-cli/issues/215
> Add hypershift cmd

- CHANGELOG.md
- Makefile
- pkg/helpers/values.go
> Use charDevice for pipe

- go.mod
- go.sum
- pkg/clusterpoolhost/clusterclaim.go
- pkg/clusterpoolhost/clusterclaimcontext.go
- pkg/clusterpoolhost/clusterpool.go
- pkg/clusterpoolhost/serviceaccount.go
- pkg/cmd/attach/clusterclaim/exec.go
- pkg/cmd/attach/hostedcluster/exec.go
- pkg/cmd/create/authrealm/exec.go
- pkg/cmd/create/cluster/exec.go
- pkg/cmd/create/cluster/exec_test.go
- pkg/cmd/create/hypershiftdeployment/exec.go
- pkg/cmd/get/config/cluster/exec.go
- pkg/cmd/get/config/hypershiftdeployment/exec.go
- pkg/cmd/install/acm/exec.go
- pkg/cmd/install/mce/cmd.go
- pkg/cmd/install/mce/exec.go
- pkg/helpers/print.go
- pkg/helpers/values.go
> Upgrade to latest applier

- pkg/cmd/get/clusterclaim/exec.go
https://github.com/stolostron/cm-cli/issues/253
https://github.com/stolostron/cm-cli/issues/252 duplicate
> Don't wait running to retrieve cc information
